// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtKbDC-THB1aZ6hpTn3OMqbXKK3MmUUcE',
    appId: '1:768494051647:web:19e621be971a2723f8738a',
    messagingSenderId: '768494051647',
    projectId: 'telegram-bot-b3a08',
    authDomain: 'telegram-bot-b3a08.firebaseapp.com',
    storageBucket: 'telegram-bot-b3a08.firebasestorage.app',
    measurementId: 'G-9REKS5N2PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMW3LTHpzNz74dVKvIKnuynALwuULjA_s',
    appId: '1:768494051647:android:74e64bcbfcfd3b8df8738a',
    messagingSenderId: '768494051647',
    projectId: 'telegram-bot-b3a08',
    storageBucket: 'telegram-bot-b3a08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmuq7SqPFuE9LYfXcykUv01jtELKDf1Og',
    appId: '1:768494051647:ios:21f10f1d0b31d7f6f8738a',
    messagingSenderId: '768494051647',
    projectId: 'telegram-bot-b3a08',
    storageBucket: 'telegram-bot-b3a08.firebasestorage.app',
    iosBundleId: 'com.example.telegramBotManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmuq7SqPFuE9LYfXcykUv01jtELKDf1Og',
    appId: '1:768494051647:ios:21f10f1d0b31d7f6f8738a',
    messagingSenderId: '768494051647',
    projectId: 'telegram-bot-b3a08',
    storageBucket: 'telegram-bot-b3a08.firebasestorage.app',
    iosBundleId: 'com.example.telegramBotManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtKbDC-THB1aZ6hpTn3OMqbXKK3MmUUcE',
    appId: '1:768494051647:web:d9c2b140867486cef8738a',
    messagingSenderId: '768494051647',
    projectId: 'telegram-bot-b3a08',
    authDomain: 'telegram-bot-b3a08.firebaseapp.com',
    storageBucket: 'telegram-bot-b3a08.firebasestorage.app',
    measurementId: 'G-4VDMR0PTR7',
  );
}
